# Kabupaten Bandung

kecamatan = {
  'Ciwidey': { 'pusat': 'Lebakmuncang', 'luas': 48.47 },
  'Rancabali': { 'pusat': 'Patengan', 'luas': 148.37 },
  'Pasirjambu': { 'pusat': 'Pasirjambu', 'luas': 239.58 },
  'Cimaung': { 'pusat': 'Cipinang', 'luas': 55 },
  'Pengalengan': { 'pusat': 'Pangalengan', 'luas': 195.41 },
  'Kertasari': { 'pusat': 'Cibeureum', 'luas': 152.07 },
  'Pacet': { 'pusat': 'Cikitu', 'luas': 91.94 },
  'Ibun': { 'pusat': 'Ibun', 'luas': 54.57 },
  'Paseh': { 'pusat': 'Tangsimekar', 'luas': 51.03 },
  'Cikancung': { 'pusat': 'Cikancung', 'luas': 40.14 },
  'Cicalengka': { 'pusat': 'Cicalengka Kulon', 'luas': 35.99 },
  'Nagreg': { 'pusat': 'Ganjarsabar', 'luas': 49.3 },
  'Rancaekek': { 'pusat': 'Rancaekek Wetan', 'luas': 45.25 },
  'Majalaya': { 'pusat': 'Majasetra', 'luas': 25.36 },
  'Solokanjeruk': { 'pusat': 'Solokanjeruk', 'luas': 24.01 },
  'Ciparay': { 'pusat': 'Pakutandang', 'luas': 46.18 },
  'Baleendah': { 'pusat': 'Baleendah', 'luas': 41.56 },
  'Arjasari': { 'pusat': 'Patrolsari', 'luas': 64.98 },
  'Banjaran': { 'pusat': 'Banjaran', 'luas': 42.92 },
  'Cangkuang': { 'pusat': 'Ciluncat', 'luas': 24.61 },
  'Pameungpeuk': { 'pusat': 'Sukasari', 'luas': 14.62 },
  'Katapang': { 'pusat': 'Sangkanhurip', 'luas': 15.72 },
  'Soreang': { 'pusat': 'Soreang', 'luas': 25.51 },
  'Kutawaringin': { 'pusat': 'Jatisari', 'luas': 47.3 },
  'Margaasih': { 'pusat': 'Margaasih', 'luas': 18.35 },
  'Margahayu': { 'pusat': 'Sukamenak', 'luas': 10.54 },
  'Dyeuhkolot': { 'pusat': 'Citeureup', 'luas': 11.03 },
  'Bojongsoang': { 'pusat': 'Bojongsoang', 'luas': 27.81 },
  'Cileunyi': { 'pusat': 'Cileunyi', 'luas': 31.58 },
  'Cilengkrang': { 'pusat': 'Jatiendah', 'luas': 30.12 },
  'Cimenyan': { 'pusat': 'Cimenyan', 'luas': 53.08 }
}
